### PR TITLE
Emojis order 271

### PR DESCRIPTION
**Pull request by DevDaniloFerrari**
Issue #271 

https://github.com/Ryczko/FormsLab/assets/40414119/68951217-a425-485f-924d-737bd8c2ff0c

image

### CODE REVIEW

**Comment by Ryczko** [comment]
Hi, thanks for your contribution, but the implementation is not satisfactory enough.
1. We don't want to get rid of the even distribution of emoticons
2. When we have emoticons in 2 rows, dragging will not work properly - we will not be able to drag from top to bottom and vice versa

**Review by Ryczko — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution, but the implementation is not satisfactory enough.

We don't want to get rid of the even distribution of emoticons
When we have emoticons in 2 rows, dragging will not work properly - we will not be able to drag from top to bottom and vice versa

**Comment by DevDaniloFerrari** [comment]
Ok, i'm gonna fix it.

**Comment by Ryczko** [comment]
@DevDaniloFerrari will you work on that or can I close PR?

**Pull request closed without merging**
